image: node:latest

stages:
  - build
  - test

build-client:
  stage: build
  only:
    - master
  script:
    - cd client
    - npm install
  artifacts:
    paths:
      - ./client/node_modules

build-server:
  stage: build
  only:
    - master
  script:
    - cd server
    - npm install
  artifacts:
    paths:
      - ./server/node_modules

prettier-client:
  stage: test
  only:
    - master
  script:
    - ./client/node_modules/.bin/prettier --check client/src/**/*.js client/test/**/*.js

prettier-server:
  stage: test
  only:
    - master
  script:
    - ./server/node_modules/.bin/prettier --check server/src/**/*.js server/test/**/*.js

flow-client:
  stage: test
  only:
    - master
  script:
    - ./client/node_modules/.bin/flow check client

flow-server:
  stage: test
  only:
    - master
  script:
    - ./server/node_modules/.bin/flow check server
